// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: protos/network/vpc.proto

package vpc

import (
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type VpcStatusMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	CodeName string `protobuf:"bytes,2,opt,name=codeName,proto3" json:"codeName,omitempty"`
}

func (x *VpcStatusMessage) Reset() {
	*x = VpcStatusMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_network_vpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VpcStatusMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VpcStatusMessage) ProtoMessage() {}

func (x *VpcStatusMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protos_network_vpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VpcStatusMessage.ProtoReflect.Descriptor instead.
func (*VpcStatusMessage) Descriptor() ([]byte, []int) {
	return file_protos_network_vpc_proto_rawDescGZIP(), []int{0}
}

func (x *VpcStatusMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *VpcStatusMessage) GetCodeName() string {
	if x != nil {
		return x.CodeName
	}
	return ""
}

type VpcMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VpcNo         string `protobuf:"bytes,1,opt,name=vpcNo,json=id,proto3" json:"vpcNo,omitempty"`
	VpcName       string `protobuf:"bytes,2,opt,name=vpcName,json=name,proto3" json:"vpcName,omitempty"`
	Ipv4CidrBlock string `protobuf:"bytes,3,opt,name=ipv4CidrBlock,json=cidrBlock,proto3" json:"ipv4CidrBlock,omitempty"`
	VpcStatus     string `protobuf:"bytes,4,opt,name=vpcStatus,json=status,proto3" json:"vpcStatus,omitempty"`
	RegionCode    string `protobuf:"bytes,5,opt,name=regionCode,json=region,proto3" json:"regionCode,omitempty"`
	CreateDate    string `protobuf:"bytes,6,opt,name=createDate,json=createdDate,proto3" json:"createDate,omitempty"`
}

func (x *VpcMessage) Reset() {
	*x = VpcMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_network_vpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VpcMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VpcMessage) ProtoMessage() {}

func (x *VpcMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protos_network_vpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VpcMessage.ProtoReflect.Descriptor instead.
func (*VpcMessage) Descriptor() ([]byte, []int) {
	return file_protos_network_vpc_proto_rawDescGZIP(), []int{1}
}

func (x *VpcMessage) GetVpcNo() string {
	if x != nil {
		return x.VpcNo
	}
	return ""
}

func (x *VpcMessage) GetVpcName() string {
	if x != nil {
		return x.VpcName
	}
	return ""
}

func (x *VpcMessage) GetIpv4CidrBlock() string {
	if x != nil {
		return x.Ipv4CidrBlock
	}
	return ""
}

func (x *VpcMessage) GetVpcStatus() string {
	if x != nil {
		return x.VpcStatus
	}
	return ""
}

func (x *VpcMessage) GetRegionCode() string {
	if x != nil {
		return x.RegionCode
	}
	return ""
}

func (x *VpcMessage) GetCreateDate() string {
	if x != nil {
		return x.CreateDate
	}
	return ""
}

type GetVpcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VpcNo string `protobuf:"bytes,1,opt,name=vpcNo,proto3" json:"vpcNo,omitempty"`
}

func (x *GetVpcRequest) Reset() {
	*x = GetVpcRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_network_vpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVpcRequest) ProtoMessage() {}

func (x *GetVpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_network_vpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVpcRequest.ProtoReflect.Descriptor instead.
func (*GetVpcRequest) Descriptor() ([]byte, []int) {
	return file_protos_network_vpc_proto_rawDescGZIP(), []int{2}
}

func (x *GetVpcRequest) GetVpcNo() string {
	if x != nil {
		return x.VpcNo
	}
	return ""
}

type GetVpcResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VpcMessage *VpcMessage `protobuf:"bytes,1,opt,name=vpc_message,json=vpcMessage,proto3" json:"vpc_message,omitempty"`
}

func (x *GetVpcResponse) Reset() {
	*x = GetVpcResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_network_vpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVpcResponse) ProtoMessage() {}

func (x *GetVpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_network_vpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVpcResponse.ProtoReflect.Descriptor instead.
func (*GetVpcResponse) Descriptor() ([]byte, []int) {
	return file_protos_network_vpc_proto_rawDescGZIP(), []int{3}
}

func (x *GetVpcResponse) GetVpcMessage() *VpcMessage {
	if x != nil {
		return x.VpcMessage
	}
	return nil
}

type ListVpcsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListVpcsRequest) Reset() {
	*x = ListVpcsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_network_vpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListVpcsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVpcsRequest) ProtoMessage() {}

func (x *ListVpcsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_network_vpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVpcsRequest.ProtoReflect.Descriptor instead.
func (*ListVpcsRequest) Descriptor() ([]byte, []int) {
	return file_protos_network_vpc_proto_rawDescGZIP(), []int{4}
}

type ListVpcsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VpcMessages []*VpcMessage `protobuf:"bytes,1,rep,name=vpc_messages,json=vpcMessages,proto3" json:"vpc_messages,omitempty"`
}

func (x *ListVpcsResponse) Reset() {
	*x = ListVpcsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_network_vpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListVpcsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVpcsResponse) ProtoMessage() {}

func (x *ListVpcsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_network_vpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVpcsResponse.ProtoReflect.Descriptor instead.
func (*ListVpcsResponse) Descriptor() ([]byte, []int) {
	return file_protos_network_vpc_proto_rawDescGZIP(), []int{5}
}

func (x *ListVpcsResponse) GetVpcMessages() []*VpcMessage {
	if x != nil {
		return x.VpcMessages
	}
	return nil
}

var File_protos_network_vpc_proto protoreflect.FileDescriptor

var file_protos_network_vpc_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x2f, 0x76, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x70, 0x63, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x42, 0x0a, 0x10, 0x56, 0x70, 0x63, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x63, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x63, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xb0, 0x01, 0x0a, 0x0a, 0x56, 0x70,
	0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x11, 0x0a, 0x05, 0x76, 0x70, 0x63, 0x4e,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x15, 0x0a, 0x07, 0x76,
	0x70, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0d, 0x69, 0x70, 0x76, 0x34, 0x43, 0x69, 0x64, 0x72, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x69, 0x64, 0x72, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x19, 0x0a, 0x09, 0x76, 0x70, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x1a, 0x0a, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x44, 0x61, 0x74, 0x65, 0x22, 0x25, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x56, 0x70, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x70, 0x63, 0x4e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x70,
	0x63, 0x4e, 0x6f, 0x22, 0x4a, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x56, 0x70, 0x63, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x76, 0x70, 0x63, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x70, 0x63, 0x2e, 0x56, 0x70, 0x63, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x0a, 0x76, 0x70, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x11, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x70, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x4e, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x70, 0x63, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0c, 0x76, 0x70, 0x63, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x70, 0x63, 0x2e, 0x56, 0x70, 0x63, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0b, 0x76, 0x70, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x32, 0xcd, 0x01, 0x0a, 0x03, 0x56, 0x70, 0x63, 0x12, 0x63, 0x0a, 0x06, 0x47, 0x65,
	0x74, 0x56, 0x70, 0x63, 0x12, 0x1a, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76,
	0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x70, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x70, 0x63, 0x2e, 0x47,
	0x65, 0x74, 0x56, 0x70, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x20, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x1a, 0x12, 0x18, 0x2f, 0x76, 0x31, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x2f, 0x76, 0x70, 0x63, 0x73, 0x2f, 0x7b, 0x76, 0x70, 0x63, 0x4e, 0x6f, 0x7d, 0x12,
	0x61, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x70, 0x63, 0x73, 0x12, 0x1c, 0x2e, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x70,
	0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x70, 0x63, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12,
	0x12, 0x10, 0x2f, 0x76, 0x31, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x76, 0x70,
	0x63, 0x73, 0x42, 0x40, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x73, 0x69, 0x6e, 0x62, 0x69, 0x68, 0x61, 0x65, 0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x72, 0x70,
	0x63, 0x2d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x2f, 0x76, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_network_vpc_proto_rawDescOnce sync.Once
	file_protos_network_vpc_proto_rawDescData = file_protos_network_vpc_proto_rawDesc
)

func file_protos_network_vpc_proto_rawDescGZIP() []byte {
	file_protos_network_vpc_proto_rawDescOnce.Do(func() {
		file_protos_network_vpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_network_vpc_proto_rawDescData)
	})
	return file_protos_network_vpc_proto_rawDescData
}

var file_protos_network_vpc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protos_network_vpc_proto_goTypes = []interface{}{
	(*VpcStatusMessage)(nil), // 0: network.vpc.VpcStatusMessage
	(*VpcMessage)(nil),       // 1: network.vpc.VpcMessage
	(*GetVpcRequest)(nil),    // 2: network.vpc.GetVpcRequest
	(*GetVpcResponse)(nil),   // 3: network.vpc.GetVpcResponse
	(*ListVpcsRequest)(nil),  // 4: network.vpc.ListVpcsRequest
	(*ListVpcsResponse)(nil), // 5: network.vpc.ListVpcsResponse
}
var file_protos_network_vpc_proto_depIdxs = []int32{
	1, // 0: network.vpc.GetVpcResponse.vpc_message:type_name -> network.vpc.VpcMessage
	1, // 1: network.vpc.ListVpcsResponse.vpc_messages:type_name -> network.vpc.VpcMessage
	2, // 2: network.vpc.Vpc.GetVpc:input_type -> network.vpc.GetVpcRequest
	4, // 3: network.vpc.Vpc.ListVpcs:input_type -> network.vpc.ListVpcsRequest
	3, // 4: network.vpc.Vpc.GetVpc:output_type -> network.vpc.GetVpcResponse
	5, // 5: network.vpc.Vpc.ListVpcs:output_type -> network.vpc.ListVpcsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_network_vpc_proto_init() }
func file_protos_network_vpc_proto_init() {
	if File_protos_network_vpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_network_vpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VpcStatusMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_network_vpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VpcMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_network_vpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVpcRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_network_vpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVpcResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_network_vpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListVpcsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_network_vpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListVpcsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_network_vpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_network_vpc_proto_goTypes,
		DependencyIndexes: file_protos_network_vpc_proto_depIdxs,
		MessageInfos:      file_protos_network_vpc_proto_msgTypes,
	}.Build()
	File_protos_network_vpc_proto = out.File
	file_protos_network_vpc_proto_rawDesc = nil
	file_protos_network_vpc_proto_goTypes = nil
	file_protos_network_vpc_proto_depIdxs = nil
}
