// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package vpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VpcClient is the client API for Vpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VpcClient interface {
	GetVpc(ctx context.Context, in *VpcSearch, opts ...grpc.CallOption) (*VpcsResponse, error)
	ListVpcs(ctx context.Context, in *VpcSearch, opts ...grpc.CallOption) (*VpcsResponse, error)
	CreateVpc(ctx context.Context, in *VpcMessage, opts ...grpc.CallOption) (*VpcsResponse, error)
	UpdateVpc(ctx context.Context, in *VpcMessage, opts ...grpc.CallOption) (*VpcsResponse, error)
	DeleteVpc(ctx context.Context, in *VpcSearch, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type vpcClient struct {
	cc grpc.ClientConnInterface
}

func NewVpcClient(cc grpc.ClientConnInterface) VpcClient {
	return &vpcClient{cc}
}

func (c *vpcClient) GetVpc(ctx context.Context, in *VpcSearch, opts ...grpc.CallOption) (*VpcsResponse, error) {
	out := new(VpcsResponse)
	err := c.cc.Invoke(ctx, "/network.vpc.Vpc/GetVpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpcClient) ListVpcs(ctx context.Context, in *VpcSearch, opts ...grpc.CallOption) (*VpcsResponse, error) {
	out := new(VpcsResponse)
	err := c.cc.Invoke(ctx, "/network.vpc.Vpc/ListVpcs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpcClient) CreateVpc(ctx context.Context, in *VpcMessage, opts ...grpc.CallOption) (*VpcsResponse, error) {
	out := new(VpcsResponse)
	err := c.cc.Invoke(ctx, "/network.vpc.Vpc/CreateVpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpcClient) UpdateVpc(ctx context.Context, in *VpcMessage, opts ...grpc.CallOption) (*VpcsResponse, error) {
	out := new(VpcsResponse)
	err := c.cc.Invoke(ctx, "/network.vpc.Vpc/UpdateVpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpcClient) DeleteVpc(ctx context.Context, in *VpcSearch, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/network.vpc.Vpc/DeleteVpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VpcServer is the server API for Vpc service.
// All implementations must embed UnimplementedVpcServer
// for forward compatibility
type VpcServer interface {
	GetVpc(context.Context, *VpcSearch) (*VpcsResponse, error)
	ListVpcs(context.Context, *VpcSearch) (*VpcsResponse, error)
	CreateVpc(context.Context, *VpcMessage) (*VpcsResponse, error)
	UpdateVpc(context.Context, *VpcMessage) (*VpcsResponse, error)
	DeleteVpc(context.Context, *VpcSearch) (*emptypb.Empty, error)
	mustEmbedUnimplementedVpcServer()
}

// UnimplementedVpcServer must be embedded to have forward compatible implementations.
type UnimplementedVpcServer struct {
}

func (UnimplementedVpcServer) GetVpc(context.Context, *VpcSearch) (*VpcsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVpc not implemented")
}
func (UnimplementedVpcServer) ListVpcs(context.Context, *VpcSearch) (*VpcsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVpcs not implemented")
}
func (UnimplementedVpcServer) CreateVpc(context.Context, *VpcMessage) (*VpcsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVpc not implemented")
}
func (UnimplementedVpcServer) UpdateVpc(context.Context, *VpcMessage) (*VpcsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVpc not implemented")
}
func (UnimplementedVpcServer) DeleteVpc(context.Context, *VpcSearch) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVpc not implemented")
}
func (UnimplementedVpcServer) mustEmbedUnimplementedVpcServer() {}

// UnsafeVpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VpcServer will
// result in compilation errors.
type UnsafeVpcServer interface {
	mustEmbedUnimplementedVpcServer()
}

func RegisterVpcServer(s grpc.ServiceRegistrar, srv VpcServer) {
	s.RegisterService(&Vpc_ServiceDesc, srv)
}

func _Vpc_GetVpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VpcSearch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpcServer).GetVpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.vpc.Vpc/GetVpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpcServer).GetVpc(ctx, req.(*VpcSearch))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vpc_ListVpcs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VpcSearch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpcServer).ListVpcs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.vpc.Vpc/ListVpcs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpcServer).ListVpcs(ctx, req.(*VpcSearch))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vpc_CreateVpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VpcMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpcServer).CreateVpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.vpc.Vpc/CreateVpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpcServer).CreateVpc(ctx, req.(*VpcMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vpc_UpdateVpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VpcMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpcServer).UpdateVpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.vpc.Vpc/UpdateVpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpcServer).UpdateVpc(ctx, req.(*VpcMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vpc_DeleteVpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VpcSearch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpcServer).DeleteVpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.vpc.Vpc/DeleteVpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpcServer).DeleteVpc(ctx, req.(*VpcSearch))
	}
	return interceptor(ctx, in, info, handler)
}

// Vpc_ServiceDesc is the grpc.ServiceDesc for Vpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Vpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "network.vpc.Vpc",
	HandlerType: (*VpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVpc",
			Handler:    _Vpc_GetVpc_Handler,
		},
		{
			MethodName: "ListVpcs",
			Handler:    _Vpc_ListVpcs_Handler,
		},
		{
			MethodName: "CreateVpc",
			Handler:    _Vpc_CreateVpc_Handler,
		},
		{
			MethodName: "UpdateVpc",
			Handler:    _Vpc_UpdateVpc_Handler,
		},
		{
			MethodName: "DeleteVpc",
			Handler:    _Vpc_DeleteVpc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/network/vpc.proto",
}
